/** Cached DOM references for game UI. */

import type { GameDom } from "../types";

export function queryDom(): GameDom {
  return {
    workspace: document.getElementById("workspace"),
    cabinetItems: document.getElementById("cabinet-items"),
    unlockedCountEl: document.getElementById("unlocked-count"),
    cabinetSearch: document.getElementById("cabinet-search") as HTMLInputElement | null,
    ingredientTypesContainer: document.getElementById("ingredient-types"),
    ingredientStatesContainer: document.getElementById("ingredient-states"),
    cookingToolbar: document.getElementById("cooking-toolbar"),
    sidebarTabButtons: document.querySelectorAll(".tab-btn[data-sidebar-tab]") as NodeListOf<HTMLElement>,
    cabinetPanel: document.getElementById("cabinet-panel"),
    skillsPanel: document.getElementById("skills-panel"),
    skillsList: document.getElementById("skills-list"),
    journalPanel: document.getElementById("journal-panel"),
    discoveryLogList: document.getElementById("discovery-log-list"),
    discoveryLogCountEl: document.getElementById("discovery-log-count"),
    achievementsPanel: document.getElementById("achievements-panel"),
    achievementsList: document.getElementById("achievements-list"),
    achievementsCountEl: document.getElementById("achievements-count"),
    achievementsProgressEl: document.getElementById("achievements-progress-fill"),
    recipeBookModal: document.getElementById("recipe-book-modal") as HTMLDialogElement | null,
    helpModal: document.getElementById("help-modal") as HTMLDialogElement | null,
    settingsModal: document.getElementById("settings-modal") as HTMLDialogElement | null,
    discoveryDialog: document.getElementById("discovery-dialog") as HTMLDialogElement | null,
    discoverySparkles: document.getElementById("discovery-sparkles"),
    discoveryKicker: document.getElementById("discovery-kicker"),
    discoveryTitle: document.getElementById("discovery-title"),
    discoveryItemContainer: document.getElementById("discovery-item-container"),
    ingredientGraphContainer: document.getElementById("ingredient-graph-container"),
    progressMapView: document.getElementById("progress-map-view"),
    btnRecipeBook: document.getElementById("btn-recipe-book") as HTMLButtonElement | null,
    btnHelp: document.getElementById("btn-help") as HTMLButtonElement | null,
    btnSettings: document.getElementById("btn-settings") as HTMLButtonElement | null,
    btnSound: document.getElementById("btn-sound") as HTMLButtonElement | null,
    btnUndoWorkspace: document.getElementById("btn-undo-workspace") as HTMLButtonElement | null,
    btnProgressGraph: document.getElementById("btn-progress-graph") as HTMLButtonElement | null,
    btnClearWorkspace: document.getElementById("btn-clear-workspace") as HTMLButtonElement | null,
    saveFileInput: document.getElementById("save-file-input") as HTMLInputElement | null,
    btnDiscoveryOk: document.getElementById("btn-discovery-ok") as HTMLButtonElement | null,
    discoveredRecipesList: document.getElementById("discovered-recipes-list"),
    settingSound: document.getElementById("setting-sound") as HTMLInputElement | null,
    settingAmbience: document.getElementById("setting-ambience") as HTMLInputElement | null,
    settingReducedMotion: document.getElementById("setting-reduced-motion") as HTMLInputElement | null,
    settingsExport: document.getElementById("settings-export") as HTMLButtonElement | null,
    settingsImport: document.getElementById("settings-import") as HTMLButtonElement | null,
    settingsReset: document.getElementById("settings-reset") as HTMLButtonElement | null,
    mechanicDiscoveryDialog: document.getElementById("mechanic-discovery-dialog") as HTMLDialogElement | null,
    mechanicSparkles: document.getElementById("mechanic-sparkles"),
    mechanicKicker: document.getElementById("mechanic-kicker"),
    mechanicTitle: document.getElementById("mechanic-title"),
    mechanicEmoji: document.getElementById("mechanic-emoji"),
    mechanicName: document.getElementById("mechanic-name"),
    mechanicDescription: document.getElementById("mechanic-description"),
    btnMechanicOk: document.getElementById("btn-mechanic-ok") as HTMLButtonElement | null
  };
}
