#!/usr/bin/env python3
"""Generate Part II regional cuisine compendium for RECIPES_REFERENCE.md"""

from __future__ import annotations
from pathlib import Path

DISHES: list[dict] = []

def d(name, culture, region, era, difficulty, primal, category, stages, history, significance):
    DISHES.append({
        "name": name, "culture": culture, "region": region, "era": era,
        "difficulty": difficulty, "primal": primal, "category": category,
        "stages": stages, "history": history, "significance": significance,
    })

def s(inp, tech, out):
    return {"input": inp, "techniques": tech, "output": out}

def add(culture, items):
    for item in items:
        d(item[0], culture, *item[1:-2], item[-2], item[-1])

# ── EAST ASIA ───────────────────────────────────────────────────────────────
add("Chinese", [
    ("Congee (Zhou)", "North China", "Ancient", 1, "grasses (rice)", "Grain",
     [s("rice, water", "hull, boil, mix", "congee")],
     "Rice porridge appears in Zhou dynasty texts as famine food and medicine.",
     "Congee remains China's gentle staple for infants, elders, and convalescence."),
    ("Jiaozi", "Northern China", "Medieval", 3, "grasses (wheat)", "Combined",
     [s("wheat flour, water", "mill, mix, bind", "dough"),
      s("pork, cabbage, ginger", "clean, mix, fill", "filling"),
      s("dough, filling", "wrap, boil, steam", "jiaozi")],
     "Dumplings spread during Han dynasty trade and became Lunar New Year symbols.",
     "Jiaozi mean reunion — shape resembles ancient gold ingots for prosperity."),
    ("Peking Duck", "Beijing", "Modern", 5, "poultry", "Meat",
     [s("duck", "clean, coat, dry", "prepared duck"),
      s("duck", "heat, smoke", "roasted duck"),
      s("pancakes, scallion, sauce", "steam, wrap", "Peking duck")],
     "Imperial kitchens perfected air-dried duck roasting by the Yuan and Ming courts.",
     "Peking duck is state banquet diplomacy — lacquered skin, ritual carving."),
    ("Mapo Tofu", "Sichuan", "Modern", 2, "seeds (soybean)", "Combined",
     [s("soybeans", "grind, boil, press", "tofu"),
      s("tofu, chili, doubanjiang", "heat, mix, coat", "mapo tofu")],
     "Chen Mapo popularized the dish in Chengdu during the Qing dynasty.",
     "Mapo tofu defines ma-la — numbing peppercorn and chili as Sichuan identity."),
    ("Fried Rice", "Southern China", "Modern", 2, "grasses (rice)", "Combined",
     [s("cooked rice", "dry", "separated rice"),
      s("rice, egg, scallion", "heat, mix, coat", "fried rice")],
     "Leftover rice stir-frying minimized waste in busy port cities.",
     "Fried rice is wok hei in a bowl — resourceful comfort across the diaspora."),
    ("Hot Pot", "Sichuan", "Medieval", 3, "mixed", "Combined",
     [s("bones, spices, chili", "boil, simmer", "broth"),
      s("meat, vegetables", "clean, strip, layer", "platters"),
      s("broth, ingredients", "boil, mix", "hot pot")],
     "Mongolian boiling vessels merged with Sichuan spice along trade routes.",
     "Hot pot is communal winter theater — everyone cooks at the table."),
    ("Mooncake", "China", "Medieval", 4, "grasses (wheat)", "Grain",
     [s("flour, syrup, oil", "mix, bind", "pastry"),
      s("lotus seeds", "boil, grind, fill", "filled cakes"),
      s("cakes", "heat, coat", "mooncakes")],
     "Mid-Autumn Festival cakes commemorated rebellion messages in Yuan legend.",
     "Mooncakes are reunion under full moon — dense sweetness shared in slices."),
    ("Wonton Soup", "Cantonese", "Modern", 3, "grasses (wheat), shellfish", "Combined",
     [s("flour, water", "mix, wrap", "wonton skins"),
      s("shrimp, pork", "clean, grind, fill", "wontons"),
      s("wontons, broth", "boil, steam", "wonton soup")],
     "Cantonese teahouses served wontons with noodles as dim sum breakfast.",
     "Wonton soup is Hong Kong soul food — silk skins in clear broth."),
    ("Dan Dan Noodles", "Sichuan", "Modern", 3, "grasses (wheat)", "Grain",
     [s("wheat flour", "mill, mix, pound", "noodles"),
      s("noodles", "boil", "cooked noodles"),
      s("noodles, chili oil, sesame", "mix, coat", "dan dan noodles")],
     "Street vendors carried dan dan poles selling noodles in Chengdu markets.",
     "Dan dan noodles are spicy street energy — nutty, fiery, bold."),
    ("Char Siu", "Cantonese", "Modern", 3, "meat", "Meat",
     [s("pork shoulder", "strip, coat", "marinated pork"),
      s("pork", "heat, smoke", "char siu")],
     "Southern Chinese roasting forks adapted to sweet fermented red glaze.",
     "Char siu hangs in every Cantonese window — caramel edge, roast aroma."),
    ("Xiaolongbao", "Shanghai", "Modern", 4, "grasses (wheat)", "Combined",
     [s("flour, water", "mix, wrap", "thin skins"),
      s("pork, gelatin stock", "grind, fill", "soup dumplings"),
      s("dumplings", "steam", "xiaolongbao")],
     "Nanxiang steamed buns evolved into soup-filled parcels by the 19th century.",
     "Xiaolongbao demands technique — bite, sip broth, then eat."),
    ("Kung Pao Chicken", "Sichuan", "Modern", 2, "poultry, nuts", "Combined",
     [s("chicken, peanuts, chili", "clean, heat, mix, coat", "kung pao chicken")],
     "Named for Qing official Ding Baozhen who favored the stir-fry.",
     "Kung pao balances sweet, sour, and ma-la in a wok flash."),
])

add("Japanese", [
    ("Ramen", "Yokohama", "Modern", 4, "grasses (wheat)", "Combined",
     [s("wheat flour", "mill, mix, pound", "noodles"),
      s("bones, soy", "boil, ferment", "broth"),
      s("noodles, broth, toppings", "boil, layer, fill", "ramen")],
     "Chinese wheat noodles met Japanese dashi after Meiji opening to trade.",
     "Ramen is regional pride — tonkotsu, shoyu, miso as edible geography."),
    ("Tempura", "Edo", "Medieval", 3, "shellfish, shoots", "Seafood",
     [s("shrimp, vegetables", "clean, peel", "prepared items"),
      s("flour, water, egg", "mix, coat", "battered items"),
      s("battered items", "heat", "tempura")],
     "Portuguese fritters influenced Japanese oil-frying during Edo trade windows.",
     "Tempura is crisp minimalism — batter lighter than the ingredient inside."),
    ("Miso Soup", "Japan", "Ancient", 1, "seeds (soybean)", "Fermented",
     [s("soybeans, koji", "ferment, grind", "miso paste"),
      s("miso, dashi", "mix, boil", "miso soup")],
     "Buddhist monks brought fermented soybean paste from China, adapted to dashi.",
     "Miso soup opens nearly every Japanese meal — daily umami ritual."),
    ("Onigiri", "Japan", "Medieval", 1, "grasses (rice)", "Grain",
     [s("rice", "steam", "steamed rice"),
      s("rice, salt, filling", "mix, wrap, bind", "onigiri")],
     "Travelers carried salted rice balls before bento culture formalized.",
     "Onigiri is portable comfort — triangle of rice, seaweed, memory."),
    ("Okonomiyaki", "Osaka", "Modern", 3, "grasses (wheat)", "Combined",
     [s("flour, eggs, cabbage", "mix, layer", "batter"),
      s("batter", "heat", "cooked pancake"),
      s("pancake", "coat", "okonomiyaki")],
     "Post-war flour surplus fueled savory pancake stalls in Osaka streets.",
     "Okonomiyaki means 'as you like it' — diner chooses toppings at the griddle."),
    ("Tonkatsu", "Tokyo", "Modern", 3, "meat", "Meat",
     [s("pork cutlet", "pound, coat", "breaded cutlet"),
      s("cutlet", "heat", "tonkatsu")],
     "Western cutlets arrived in Meiji era and were breaded with Japanese panko.",
     "Tonkatsu with shredded cabbage is yōshoku comfort — Western form, Japanese soul."),
    ("Yakitori", "Japan", "Modern", 2, "poultry", "Meat",
     [s("chicken", "clean, strip", "chicken pieces"),
      s("pieces", "skewer, coat, heat", "yakitori")],
     "Edo street stalls grilled skewered chicken over charcoal after meat bans eased.",
     "Yakitori izakaya culture turns every chicken part into smoky delicacy."),
    ("Matcha Wagashi", "Kyoto", "Modern", 4, "seeds (beans)", "Fruit",
     [s("azuki beans", "boil, grind, mix", "bean paste"),
      s("rice flour, sugar, matcha", "mix, steam, wrap", "wagashi")],
     "Tea ceremony aesthetics demanded seasonal sweets paired with bitter matcha.",
     "Wagashi are edible art — moon, maple, and season in one bite."),
    ("Udon", "Kagawa", "Ancient", 2, "grasses (wheat)", "Grain",
     [s("wheat flour", "mill, pound, mix", "udon dough"),
      s("dough", "boil", "udon noodles"),
      s("noodles, dashi", "heat, layer", "udon soup")],
     "Thick wheat noodles spread from China through Buddhist temple kitchens.",
     "Sanuki udon in Kagawa is chew as religion — springy strands in clear broth."),
    ("Takoyaki", "Osaka", "Modern", 2, "shellfish (octopus)", "Seafood",
     [s("flour, dashi", "mix", "batter"),
      s("octopus, batter", "fill, heat", "takoyaki")],
     "Street vendors in Osaka invented ball-shaped octopus fritters in the 1930s.",
     "Takoyaki is festival food — crispy shell, molten center, dancing bonito."),
])

add("Korean", [
    ("Bibimbap", "Jeonju", "Modern", 2, "grasses (rice)", "Combined",
     [s("rice", "steam", "rice"),
      s("vegetables, beef, egg", "clean, heat, layer", "toppings"),
      s("rice, toppings, gochujang", "mix, coat", "bibimbap")],
     "Royal court banchan merged with peasant stone bowls in Jeonju tradition.",
     "Bibimbap is harmony in a bowl — color, texture, and heat before mixing."),
    ("Kimchi Jjigae", "Korea", "Modern", 2, "fermented", "Fermented",
     [s("aged kimchi, pork, tofu", "chop, boil, simmer", "kimchi jjigae")],
     "Sour kimchi too fermented for fresh eating becomes stew base in every household.",
     "Kimchi jjigae is home after work — spicy, sour, deeply familiar steam."),
    ("Galbi", "Korea", "Modern", 3, "meat", "Meat",
     [s("beef short ribs", "clean, coat", "marinated ribs"),
      s("ribs", "heat", "galbi")],
     "Pear-tenderized soy marinades define Korean barbecue alongside tabletop grills.",
     "Galbi at Korean BBQ is celebration — scissors, lettuce wraps, shared fire."),
    ("Japchae", "Korea", "Modern", 3, "tubers (starch)", "Combined",
     [s("sweet potato starch", "mix, press, dry, boil", "glass noodles"),
      s("noodles, vegetables, beef", "heat, mix, coat", "japchae")],
     "Joseon court feast dish using Chinese glass noodle technique with Korean vegetables.",
     "Japchae marks holidays — slippery noodles, sesame shine, festive color."),
    ("Tteokbokki", "Seoul", "Modern", 2, "grasses (rice)", "Grain",
     [s("rice flour", "pound, steam, shape", "tteok"),
      s("tteok, gochujang", "boil, coat", "tteokbokki")],
     "Street vendors in 1950s Seoul popularized spicy sauce on chewy rice cylinders.",
     "Tteokbokki is after-school nostalgia — sweet heat at pojangmacha stalls."),
    ("Sundubu Jjigae", "Korea", "Modern", 2, "seeds (soybean)", "Combined",
     [s("soft tofu, seafood, kimchi", "boil, simmer, fill", "sundubu jjigae")],
     "Soft silken tofu stews gained popularity with Korean seafood and chili paste.",
     "Sundubu arrives bubbling in stone — comfort that scorches the tongue."),
    ("Samgyeopsal", "Korea", "Modern", 2, "meat", "Meat",
     [s("pork belly", "strip, layer", "sliced belly"),
      s("belly", "heat", "grilled samgyeopsal")],
     "Thick-cut belly grilled at table became post-war Korean comfort ritual.",
     "Samgyeopsal with soju is Friday night — fat crackle, lettuce, garlic."),
    ("Haemul Pajeon", "Korea", "Modern", 2, "shellfish, shoots", "Combined",
     [s("flour, eggs, scallions, seafood", "mix, layer, heat", "seafood pancake")],
     "Rainy-day pancakes with scallions and shellfish fill Korean tavern menus.",
     "Pajeon with makgeolli is weather magic — crispy edges, shared plate."),
])

add("Vietnamese", [
    ("Phở", "Hanoi", "Modern", 3, "grasses (rice), meat", "Combined",
     [s("bones, spices", "boil, simmer", "broth"),
      s("rice noodles", "boil", "noodles"),
      s("broth, noodles, beef, herbs", "layer, fill", "phở")],
     "French colonial pot-au-feu met Vietnamese rice noodles and star anise.",
     "Phở is national breakfast — steam, herbs, and hours of bone patience."),
    ("Bánh Mì", "Saigon", "Modern", 2, "grasses (wheat)", "Combined",
     [s("flour", "ferment, heat", "baguette"),
      s("bread, pork, pickles, herbs", "fill, layer", "bánh mì")],
     "French baguettes adopted into Vietnamese street sandwiches after colonial era.",
     "Bánh mì is crunch, pickle, and cilantro — Saigon in one hand."),
    ("Bún Chả", "Hanoi", "Modern", 3, "grasses (rice), meat", "Combined",
     [s("pork", "grind, form, heat", "grilled patties"),
      s("rice noodles, herbs, dipping sauce", "boil, layer", "bún chả")],
     "Obama and Bourdain ate this Hanoi dish — charcoal pork with vermicelli.",
     "Bún chả is lunch in the alley — smoke, nuoc cham, communal bowls."),
    ("Gỏi Cuốn", "Vietnam", "Modern", 2, "shellfish, shoots", "Combined",
     [s("shrimp, herbs, rice paper", "clean, wrap", "fresh spring rolls")],
     "Fresh rolls contrast fried imperial court snacks with raw herb brightness.",
     "Gỏi cuốn is summer transparency — see every ingredient through rice paper."),
    ("Cà Phê Sữa Đá", "Saigon", "Modern", 1, "seeds (coffee)", "Fermented",
     [s("coffee beans", "roast, grind, press", "strong coffee"),
      s("coffee, condensed milk, ice", "mix, layer", "Vietnamese iced coffee")],
     "French drip met sweetened condensed milk in tropical heat.",
     "Ca phe sua da is slow drip under sun — bitter-sweet pause on plastic stool."),
    ("Bún Bò Huế", "Huế", "Modern", 3, "grasses (rice), meat", "Combined",
     [s("beef bones, lemongrass, chili", "boil, simmer", "spicy broth"),
      s("rice noodles, beef, pork", "boil, layer", "bún bò Huế")],
     "Imperial capital Huế developed lemongrass-heavy noodle soup distinct from phở.",
     "Bún bò Huế is central Vietnam fire — shrimp paste depth, chili oil ring."),
])

add("Thai", [
    ("Pad Thai", "Bangkok", "Modern", 2, "grasses (rice)", "Combined",
     [s("rice noodles", "soak, heat", "wok noodles"),
      s("noodles, shrimp, tamarind, egg", "mix, coat", "pad thai")],
     "Prime Minister Plaek promoted pad thai in the 1930s to build national identity.",
     "Pad Thai is tourist gateway and local staple — sweet-sour wok char."),
    ("Tom Yum Goong", "Central Thailand", "Modern", 2, "shellfish", "Seafood",
     [s("shrimp, lemongrass, galangal", "clean, boil, mix", "tom yum soup")],
     "Ayutthaya river trade brought chili and lime to sour-spicy broths.",
     "Tom yum is hot-sour lightning — lemongrass perfume, chili sting."),
    ("Green Curry", "Central Thailand", "Modern", 3, "mixed", "Combined",
     [s("chili, herbs", "grind, mix", "green curry paste"),
      s("paste, coconut, chicken", "heat, simmer", "green curry")],
     "Persian Muslim traders introduced dried spices; Thai cooks added fresh herbs.",
     "Green curry is coconut silk with green chili heat — balance not burn."),
    ("Som Tam", "Isaan", "Modern", 2, "fruits (papaya)", "Fruit",
     [s("green papaya", "peel, pound", "shredded papaya"),
      s("papaya, chili, lime, peanuts", "pound, mix", "som tam")],
     "Lao papaya salad crossed the Mekong into northeast Thai street culture.",
     "Som tam is mortar percussion — spicy, sour, crunchy Isaan afternoon."),
    ("Mango Sticky Rice", "Thailand", "Modern", 2, "grasses (rice), fruits", "Combined",
     [s("glutinous rice", "soak, steam", "sticky rice"),
      s("rice, coconut, mango", "mix, layer", "mango sticky rice")],
     "Northern Thai dessert pairs seasonal mango with coconut-sweetened glutinous rice.",
     "Khao niao mamuang is summer finale — ripe mango, salty-sweet rice."),
    ("Massaman Curry", "Southern Thailand", "Medieval", 3, "mixed", "Combined",
     [s("spices, chili", "grind, mix", "massaman paste"),
      s("paste, coconut, beef, peanuts", "heat, simmer", "massaman curry")],
     "Persian and Indian Muslim traders brought cardamom and peanuts south.",
     "Massaman is Thailand's most aromatic curry — sweet spice, slow braise."),
])

# ── SOUTH ASIA ──────────────────────────────────────────────────────────────
add("Indian (North)", [
    ("Naan", "North India", "Medieval", 2, "grasses (wheat)", "Grain",
     [s("flour, yogurt", "mix, ferment", "dough"),
      s("dough", "heat", "naan")],
     "Central Asian tandoor ovens arrived with Mughal courts.",
     "Naan is tear-and-dip bread — char bubbles from clay oven wall."),
    ("Dal Tadka", "Punjab", "Modern", 1, "seeds (lentils)", "Grain",
     [s("lentils", "boil, mash", "dal"),
      s("dal, spices, ghee", "heat, mix", "dal tadka")],
     "Lentil stews sustained Indus valley agriculture for millennia.",
     "Dal tadka is weeknight India — tempered spices crackle on top."),
    ("Butter Chicken", "Delhi", "Modern", 3, "poultry", "Meat",
     [s("chicken", "coat, heat", "tandoori chicken"),
      s("chicken, tomato, butter, cream", "mix, simmer", "butter chicken")],
     "Mot Mahal restaurant repurposed leftover tandoori chicken in tomato gravy in 1950s.",
     "Butter chicken is diaspora ambassador — mild, rich, universally loved."),
    ("Samosa", "North India", "Medieval", 3, "grasses (wheat)", "Combined",
     [s("flour", "mix, bind", "pastry"),
      s("potato, peas, spices", "heat, fill", "filled samosas"),
      s("samosas", "heat", "fried samosas")],
     "Central Asian sanbosag traveled the Silk Road into Indian street food.",
     "Samosas are triangle diplomacy — crispy shell, spiced potato heart."),
    ("Chole Bhature", "Punjab", "Modern", 3, "seeds, grasses", "Combined",
     [s("chickpeas", "soak, boil, mix", "chole"),
      s("flour", "ferment, heat", "bhature"),
      s("chole, bhature", "layer", "chole bhature")],
     "Punjabi chickpea curry with fried leavened bread fuels Delhi street mornings.",
     "Chole bhature is Sunday indulgence — puffy bread, tangy chickpeas."),
    ("Paratha", "North India", "Medieval", 2, "grasses (wheat)", "Grain",
     [s("flour, ghee", "mix, layer, heat", "paratha")],
     "Layered flatbreads developed across the subcontinent with regional fillings.",
     "Paratha with pickle is breakfast armor — flaky, greasy, satisfying."),
    ("Rogan Josh", "Kashmir", "Medieval", 4, "meat", "Meat",
     [s("lamb, yogurt, spices", "coat, heat, simmer", "rogan josh")],
     "Mughal and Persian influences created Kashmir's crimson slow-cooked lamb.",
     "Rogan josh is Wazwan centerpiece — deep red, aromatic, celebratory."),
    ("Tandoori Chicken", "Punjab", "Modern", 3, "poultry", "Meat",
     [s("chicken", "clean, coat (yogurt spice)", "marinated chicken"),
      s("chicken", "heat", "tandoori chicken")],
     "Kundan Lal Gujral popularized clay-oven chicken at Moti Mahal.",
     "Tandoori chicken is crimson char — yogurt tender, spice smoke."),
])

add("Indian (South)", [
    ("Dosa", "Tamil Nadu", "Ancient", 3, "grasses (rice), seeds", "Grain",
     [s("rice, urad dal", "ferment, grind", "batter"),
      s("batter", "heat", "dosa")],
     "Fermented rice-lentil crepes appear in Sangam-era Tamil literature.",
     "Dosa is South Indian breakfast king — crisp lace, sambar dip."),
    ("Idli", "Tamil Nadu", "Ancient", 2, "grasses (rice), seeds", "Grain",
     [s("rice, urad dal", "ferment, grind", "batter"),
      s("batter", "steam", "idli")],
     "Steamed fermented cakes offered in temples as pure vegetarian sustenance.",
     "Idli is soft cloud — fermented tang, coconut chutney partner."),
    ("Sambar", "South India", "Medieval", 2, "seeds, tubers", "Combined",
     [s("toor dal, tamarind, vegetables", "boil, mix", "sambar")],
     "Maratha rulers influenced tamarind-lentil stew across southern states.",
     "Sambar unites dosa, idli, and rice — tangy lentil backbone."),
    ("Hyderabadi Biryani", "Hyderabad", "Medieval", 4, "grasses (rice), meat", "Combined",
     [s("basmati rice", "soak, layer", "parboiled rice"),
      s("marinated meat", "coat, layer", "raw meat layer"),
      s("rice, meat", "heat, steam", "dum biryani")],
     "Nizam kitchens perfected dum cooking merging Persian pilaf with Deccan spice.",
     "Hyderabadi biryani is sealed-pot ceremony — aromatic rice, tender meat."),
    ("Rasam", "South India", "Medieval", 1, "fruits (tamarind)", "Combined",
     [s("tamarind, tomato, pepper", "boil, mix", "rasam")],
     "Pepper broth predates chili as South India's warming digestive tonic.",
     "Rasam is monsoon medicine — thin, peppery, poured over rice."),
    ("Uttapam", "South India", "Modern", 2, "grasses (rice)", "Grain",
     [s("dosa batter, vegetables", "mix, heat", "uttapam")],
     "Thick vegetable-topped pancakes use leftover dosa batter.",
     "Uttapam is dosa's generous cousin — toppings embedded in the batter."),
    ("Fish Curry (Meen Kuzhambu)", "Kerala", "Modern", 2, "fish", "Seafood",
     [s("fish, coconut, tamarind", "clean, grind, boil", "fish curry")],
     "Coastal Kerala pairs coconut milk and tamarind with backwater catch.",
     "Meen curry on red rice is monsoon Kerala — sour, coconut, coastal."),
])

add("Pakistani", [
    ("Nihari", "Lahore", "Medieval", 4, "meat", "Meat",
     [s("beef shank, spices", "heat, simmer", "nihari")],
     "Mughal overnight stew became Old Delhi and Lahore breakfast tradition.",
     "Nihari at dawn is slow-cooked devotion — bone marrow, naan tear."),
    ("Seekh Kebab", "Punjab", "Medieval", 3, "meat", "Meat",
     [s("minced meat, spices", "mix, skewer", "kebabs"),
      s("kebabs", "heat", "seekh kebab")],
     "Ground meat on skewers cooked in tandoor spread from Central Asia.",
     "Seekh kebab is charcoal perfume — spiced mince, charred edge."),
    ("Biryani (Sindhi)", "Sindh", "Medieval", 4, "grasses (rice), meat", "Combined",
     [s("rice, meat, spices", "layer, heat, steam", "Sindhi biryani")],
     "Sindhi traders carried biryani along Indus valley spice routes.",
     "Sindhi biryani is potato-and-meat layers — aromatic, celebratory pot."),
])

add("Sri Lankan", [
    ("Hoppers (Appa)", "Sri Lanka", "Medieval", 2, "grasses (rice)", "Grain",
     [s("rice flour, coconut milk", "ferment, mix", "batter"),
      s("batter", "heat", "hoppers")],
     "Bowl-shaped fermented crepes cooked in small round pans.",
     "Egg hopper at breakfast is Sri Lankan morning — crisp edge, soft center."),
    ("Kottu Roti", "Sri Lanka", "Modern", 2, "grasses (wheat)", "Combined",
     [s("godamba roti", "chop, heat, mix", "kottu roti")],
     "Chopped flatbread stir-fried on griddle with curry and vegetables.",
     "Kottu clatter on steel blades is street soundtrack — spicy, shredded comfort."),
])

# ── SOUTHEAST ASIA (continued) ──────────────────────────────────────────────
add("Indonesian", [
    ("Nasi Goreng", "Java", "Modern", 2, "grasses (rice)", "Combined",
     [s("rice, kecap, egg", "heat, mix, coat", "nasi goreng")],
     "Dutch colonial leftovers met Indonesian sweet soy and sambal.",
     "Nasi goreng is Indonesia's national plate — wok smoke, fried egg crown."),
    ("Rendang", "West Sumatra", "Medieval", 5, "meat", "Meat",
     [s("beef, coconut, spices", "heat, dry, simmer", "rendang")],
     "Minangkabau slow-cooked beef in coconut until almost dry for preservation.",
     "Rendang is patience as flavor — hours reduce spice and coconut to paste."),
    ("Satay", "Java", "Medieval", 2, "meat", "Meat",
     [s("meat", "strip, skewer, coat", "skewers"),
      s("skewers", "heat", "satay")],
     "Arab traders brought kebab tradition; Java added peanut sauce.",
     "Satay is street smoke — charcoal strips, peanut dip, quick eat."),
    ("Gado-Gado", "Java", "Modern", 2, "shoots, seeds", "Combined",
     [s("vegetables, tofu, egg", "boil, steam, layer", "salad"),
      s("peanut sauce", "grind, mix", "gado-gado")],
     "Indonesian mixed salad with peanut dressing bridges vegetable and protein.",
     "Gado-gado is vegetarian feast — peanut richness over blanched vegetables."),
    ("Gudeg", "Yogyakarta", "Modern", 3, "fruits (jackfruit)", "Combined",
     [s("young jackfruit", "boil, simmer", "gudeg")],
     "Sweet jackfruit stew cooked for hours in coconut and palm sugar.",
     "Gudeg is Javanese sweetness — tender jackfruit, coconut, morning ritual."),
])

add("Malaysian", [
    ("Nasi Lemak", "Malaysia", "Modern", 2, "grasses (rice)", "Combined",
     [s("rice, coconut milk", "steam", "coconut rice"),
      s("rice, sambal, anchovies, egg", "layer", "nasi lemak")],
     "Malay breakfast rice cooked in coconut milk with sambal and crispy anchovies.",
     "Nasi lemak is Malaysia wrapped in banana leaf — spicy, fragrant morning."),
    ("Laksa", "Penang", "Modern", 3, "grasses (rice)", "Combined",
     [s("rice noodles", "boil", "noodles"),
      s("broth, seafood", "simmer, layer", "laksa")],
     "Peranakan Chinese-Malay fusion created multiple regional laksa styles.",
     "Laksa is sour-spicy-coconut argument — Penang assam vs Sarawak creamy."),
    ("Char Kway Teow", "Penang", "Modern", 2, "grasses (rice)", "Combined",
     [s("rice noodles, shrimp, egg", "heat, mix, coat", "char kway teow")],
     "Wok-fried flat rice noodles with dark soy from Chinese-Malay hawker stalls.",
     "Char kway teow is wok hei on a plate — smoky noodles, prawn, cockles."),
])

add("Filipino", [
    ("Adobo", "Philippines", "Medieval", 2, "meat", "Meat",
     [s("pork or chicken, vinegar, soy", "coat, simmer", "adobo")],
     "Spanish name, indigenous vinegar-braise technique predating colonization.",
     "Adobo is Filipino default — tangy, garlicky, better the next day."),
    ("Sinigang", "Philippines", "Modern", 2, "mixed", "Combined",
     [s("pork, tamarind, vegetables", "boil, mix", "sinigang")],
     "Sour soup using tamarind or guava defines Filipino comfort cooking.",
     "Sinigang is rainy-season hug — sour broth, tender meat, vegetables."),
    ("Lumpia", "Philippines", "Modern", 2, "grasses (wheat)", "Combined",
     [s("wrapper, vegetables, pork", "fill, wrap, heat", "lumpia")],
     "Chinese spring rolls adapted to Filipino fiesta tables.",
     "Lumpia is party finger food — crunch, sweet-sour dip, always gone first."),
    ("Lechon", "Cebu", "Modern", 4, "meat", "Meat",
     [s("whole pig", "clean, coat, skewer", "prepared pig"),
      s("pig", "heat, rotate", "lechon")],
     "Spanish roast pig tradition perfected in Cebu with crispy skin.",
     "Lechon is fiesta centerpiece — crackling skin, whole-community feast."),
    ("Kare-Kare", "Philippines", "Modern", 3, "mixed", "Combined",
     [s("oxtail, peanut, vegetables", "boil, grind, mix", "kare-kare")],
     "Peanut stew from Kapampangan kitchens served at festive gatherings.",
     "Kare-kare with bagoong is special occasion — rich, nutty, communal."),
])

# ── MIDDLE EAST & NORTH AFRICA ──────────────────────────────────────────────
add("Levantine", [
    ("Falafel", "Levant", "Medieval", 2, "seeds (chickpeas)", "Combined",
     [s("chickpeas, herbs", "soak, grind, mix", "falafel mix"),
      s("mix", "form, heat", "falafel")],
     "Egyptian fava or Levantine chickpea fritters fried in street carts.",
     "Falafel in pita is Middle East fast food — herb green, tahini drip."),
    ("Hummus", "Levant", "Ancient", 1, "seeds (chickpeas)", "Fermented",
     [s("chickpeas, tahini, lemon", "boil, grind, mix", "hummus")],
     "Chickpea puree appears in medieval Cairo cookbooks.",
     "Hummus is shared dip diplomacy — tahini silk, olive oil swirl."),
    ("Tabbouleh", "Levant", "Modern", 1, "grasses (bulgur), shoots", "Combined",
     [s("bulgur, parsley, tomato, mint", "chop, mix", "tabbouleh")],
     "Levantine herb salad predates tomato's arrival in the region.",
     "Tabbouleh is parsley mountain — lemon bright, bulgur whisper."),
    ("Kibbeh", "Lebanon", "Medieval", 4, "meat, grasses", "Combined",
     [s("bulgur, minced lamb", "mix, fill, form", "kibbeh"),
      s("kibbeh", "heat", "fried kibbeh")],
     "Ancient Assyrian raw and cooked lamb-in-bulgur shells.",
     "Kibbeh is Lebanon's edible sculpture — cracked wheat, spiced meat."),
    ("Shawarma", "Levant", "Modern", 2, "meat", "Meat",
     [s("marinated meat", "skewer, heat", "shawarma"),
      s("meat, bread, tahini", "wrap, layer", "shawarma sandwich")],
     "Ottoman vertical rotisserie met Levantine spice marinades.",
     "Shawarma is midnight street stack — shaved edge, garlic sauce."),
    ("Manakish", "Lebanon", "Medieval", 2, "grasses (wheat)", "Grain",
     [s("flour", "mix, ferment", "dough"),
      s("dough, za'atar, oil", "coat, heat", "manakish")],
     "Flatbread topped with za'atar spread baked for breakfast across Levant.",
     "Manakish with tea is Lebanese morning — thyme, sesame, warm dough."),
])

add("Turkish", [
    ("Döner Kebab", "Anatolia", "Modern", 2, "meat", "Meat",
     [s("marinated lamb", "skewer, heat", "döner"),
      s("meat, bread, vegetables", "wrap, layer", "döner sandwich")],
     "Vertical rotisserie cooking spread from Ottoman kitchens to global streets.",
     "Döner is Istanbul late night — shaved meat, yogurt sauce, flatbread."),
    ("Lahmacun", "Turkey", "Medieval", 2, "grasses (wheat), meat", "Combined",
     [s("dough", "mix, roll", "thin base"),
      s("minced meat, herbs", "coat, heat", "lahmacun")],
     "Thin meat-topped flatbread baked quickly in stone ovens.",
     "Lahmacun is Turkish pizza — squeeze lemon, roll, eat walking."),
    ("Börek", "Turkey", "Medieval", 3, "grasses (wheat)", "Combined",
     [s("phyllo, cheese or meat", "layer, fill, heat", "börek")],
     "Layered pastry from Central Asian yufka tradition in Ottoman palace kitchens.",
     "Börek is flaky layers — cheese melt, buttery crunch, breakfast tray."),
    ("Menemen", "Turkey", "Modern", 1, "eggs, fruits (tomato)", "Egg",
     [s("eggs, tomato, pepper", "heat, mix", "menemen")],
     "Scrambled eggs with tomato and pepper in Anatolian village kitchens.",
     "Menemen is Turkish brunch — runny eggs, bread tear, shared pan."),
    ("Baklava", "Gaziantep", "Medieval", 5, "nuts, grasses", "Combined",
     [s("phyllo, pistachio, butter", "layer, fill, heat", "baklava")],
     "Ottoman palace kitchens refined layered nut pastry with syrup.",
     "Gaziantep baklava is honeyed geometry — forty layers, pistachio green."),
])

add("Persian", [
    ("Chelow Kabab", "Iran", "Medieval", 3, "grasses (rice), meat", "Combined",
     [s("rice", "wash, boil, steam", "chelow"),
      s("lamb", "skewer, heat", "kabob"),
      s("rice, kabob, butter", "layer", "chelow kabab")],
     "Persian steamed rice with saffron butter served beside charcoal kebabs.",
     "Chelow kabab is Iranian Sunday — saffron rice, tomato, grilled lamb."),
    ("Tahdig", "Iran", "Medieval", 3, "grasses (rice)", "Grain",
     [s("rice, oil or bread", "layer, heat", "tahdig")],
     "Crispy rice crust formed at bottom of Persian pot is prized portion.",
     "Tahdig is fought over at table — golden crunch, communal treasure."),
    ("Fesenjan", "Iran", "Medieval", 4, "nuts, poultry", "Combined",
     [s("walnuts", "grind", "walnut paste"),
      s("pomegranate, chicken", "mix, simmer", "fesenjan")],
     "Pomegranate-walnut stew from northern Iran served at celebrations.",
     "Fesenjan is sweet-sour depth — walnut body, pomegranate tang."),
    ("Ash Reshteh", "Iran", "Ancient", 3, "grasses, seeds", "Combined",
     [s("herbs, beans, noodles", "chop, boil, mix", "ash reshteh")],
     "Thick noodle-herb soup eaten during Nowruz and cold evenings.",
     "Ash reshteh is Persian comfort — kashk swirl, herb green, noodle chew."),
])

add("Moroccan", [
    ("Couscous", "Morocco", "Medieval", 3, "grasses (semolina)", "Grain",
     [s("semolina", "roll, steam", "couscous"),
      s("couscous, vegetables, meat", "steam, layer", "couscous royale")],
     "Berber steamed grain became Friday family meal across Maghreb.",
     "Couscous on Friday is Moroccan rhythm — steam, seven vegetables, shared pot."),
    ("Tagine", "Morocco", "Medieval", 3, "mixed", "Combined",
     [s("meat, vegetables, spices", "layer, heat, simmer", "tagine")],
     "Conical clay lid condenses steam back into slow braise.",
     "Tagine is patience in pottery — sweet prune, savory lamb, communal dip."),
    ("Harira", "Morocco", "Medieval", 2, "seeds, grasses", "Combined",
     [s("lentils, chickpeas, tomato", "boil, mix", "harira")],
     "Ramadan sunset soup breaks fast across Moroccan homes.",
     "Harira at iftar is lentil warmth — dates after, community table."),
    ("Pastilla", "Fez", "Medieval", 4, "poultry, nuts", "Combined",
     [s("pigeon or chicken, almonds", "heat, grind, fill", "filling"),
      s("phyllo, filling", "layer, heat", "pastilla")],
     "Sweet-savory pie from Andalusian refugees in imperial Fez.",
     "Pastilla is sugar on meat — cinnamon dust, almond crunch, celebration."),
])

add("Egyptian", [
    ("Koshari", "Cairo", "Modern", 2, "grasses (rice), seeds", "Combined",
     [s("rice, lentils, pasta", "boil, layer", "koshari base"),
      s("base, tomato sauce, chickpeas", "coat, mix", "koshari")],
     "Street stall layering of British Indian and Italian colonial staples.",
     "Koshari is Cairo carb tower — vinegar garlic, chili crunch, cheap feast."),
    ("Ful Medames", "Egypt", "Ancient", 1, "seeds (fava)", "Fermented",
     [s("fava beans", "soak, boil, mash", "ful medames")],
     "Pharaonic fava stew remains Egypt's breakfast of millions.",
     "Ful with bread is Cairo dawn — cumin, oil, working-class fuel."),
])

# ── EUROPE ──────────────────────────────────────────────────────────────────
add("French", [
    ("Coq au Vin", "Burgundy", "Medieval", 4, "poultry", "Meat",
     [s("chicken, wine, mushrooms", "coat, heat, simmer", "coq au vin")],
     "Peasant braised chicken in wine became haute cuisine staple.",
     "Coq au vin is Burgundy in a pot — wine depth, mushroom earth."),
    ("Ratatouille", "Provence", "Modern", 2, "fruits (vegetables)", "Combined",
     [s("eggplant, zucchini, tomato", "peel, chop, heat, layer", "ratatouille")],
     "Niçoise vegetable stew celebrates Mediterranean summer harvest.",
     "Ratatouille is sun on a plate — olive oil, herbs, slow meld."),
    ("Croissant", "Paris", "Modern", 4, "grasses (wheat)", "Grain",
     [s("flour, butter", "mix, layer, fold, heat", "croissant")],
     "Austrian kipferl evolved into laminated French breakfast pastry.",
     "Croissant is butter architecture — flaky layers, café pause."),
    ("Bouillabaisse", "Marseille", "Medieval", 4, "shellfish, fish", "Seafood",
     [s("mixed seafood", "clean, boil, simmer", "bouillabaisse")],
     "Fishermen's catch-all stew from Marseille port became luxury dish.",
     "Bouillabaisse is Mediterranean in a bowl — saffron, rouille, bread."),
    ("Crème Brûlée", "France", "Modern", 4, "eggs", "Egg",
     [s("cream, egg yolk, sugar", "mix, heat", "custard"),
      s("custard", "coat (sugar), heat", "crème brûlée")],
     "Custard with caramelized sugar cap from French and Catalan traditions.",
     "Crème brûlée is crack spoon moment — silk beneath, glass sugar top."),
    ("Cassoulet", "Toulouse", "Medieval", 5, "seeds, meat", "Combined",
     [s("white beans, duck, sausage", "soak, layer, heat, simmer", "cassoulet")],
     "Languedoc bean casserole slow-cooked until crust forms on top.",
     "Cassoulet is winter project — duck confit, sausage, bean depth."),
    ("Quiche Lorraine", "Lorraine", "Medieval", 3, "eggs, grasses", "Combined",
     [s("pastry", "mix, bind", "crust"),
      s("eggs, cream, bacon", "mix, fill, heat", "quiche")],
     "Savory egg custard in pastry from Franco-German border region.",
     "Quiche Lorraine is brunch classic — egg silk, bacon salt, buttery crust."),
])

add("Italian", [
    ("Pizza Margherita", "Naples", "Modern", 2, "grasses (wheat)", "Combined",
     [s("flour, water", "ferment, mix", "dough"),
      s("dough, tomato, mozzarella", "coat, heat", "pizza")],
     "Neapolitan flatbread topped with tomato after Americas contact.",
     "Pizza Margherita is tricolor flag — basil, tomato, mozzarella."),
    ("Pasta Carbonara", "Rome", "Modern", 3, "grasses (wheat), eggs", "Combined",
     [s("wheat flour", "mill, mix", "pasta"),
      s("pasta, egg, guanciale, pecorino", "boil, mix, coat", "carbonara")],
     "Roman pasta with egg and cured pork — no cream in authentic version.",
     "Carbonara is Roman midnight — silky egg, pepper bite, guanciale fat."),
    ("Risotto alla Milanese", "Milan", "Medieval", 3, "grasses (rice)", "Grain",
     [s("rice, saffron, stock", "heat, mix", "risotto")],
     "Arborio rice stirred with saffron from Lombardy cathedral builders.",
     "Risotto Milanese is golden patience — saffron stain, creamy bite."),
    ("Lasagna", "Emilia-Romagna", "Medieval", 4, "grasses (wheat)", "Combined",
     [s("pasta sheets, ragù, béchamel", "layer, heat", "lasagna")],
     "Layered pasta from Bologna became global comfort casserole.",
     "Lasagna is Sunday nonna — ragù depth, cheese bubble, family pan."),
    ("Osso Buco", "Milan", "Medieval", 4, "meat", "Meat",
     [s("veal shank", "coat, heat, simmer", "osso buco")],
     "Braised marrow bones in white wine and gremolata from Lombardy.",
     "Osso buco is marrow spoon ritual — gremolata bright, braised fall-apart."),
    ("Pesto alla Genovese", "Liguria", "Modern", 2, "shoots (basil), nuts", "Combined",
     [s("basil, pine nuts, garlic", "grind, mix", "pesto"),
      s("pesto, pasta", "coat", "pesto pasta")],
     "Mortar-ground basil sauce from Genoa port city.",
     "Pesto is Ligurian green — basil perfume, pine nut, olive oil."),
    ("Tiramisu", "Veneto", "Modern", 3, "eggs", "Egg",
     [s("mascarpone, egg, coffee, ladyfingers", "mix, layer, chill", "tiramisu")],
     "Coffee-soaked dessert invented in Treviso veneto region 1960s.",
     "Tiramisu means pick-me-up — espresso soak, cocoa dust, creamy lift."),
    ("Gelato", "Italy", "Ancient", 3, "fruits, eggs", "Fruit",
     [s("milk, sugar, flavoring", "mix, freeze", "gelato")],
     "Roman ice with snow from Alps evolved into dense Italian frozen cream.",
     "Gelato is passeggiata reward — dense, slow-melt, flavor pure."),
])

add("Spanish", [
    ("Paella", "Valencia", "Medieval", 4, "grasses (rice), shellfish", "Combined",
     [s("rice, saffron, stock", "heat, layer", "rice base"),
      s("seafood, chicken", "clean, heat", "toppings"),
      s("rice, toppings", "heat, layer", "paella")],
     "Valencian field workers cooked rice in wide pan over open fire.",
     "Paella is socarrat hunt — crispy bottom, saffron gold, communal pan."),
    ("Gazpacho", "Andalusia", "Medieval", 1, "fruits (tomato)", "Combined",
     [s("tomato, cucumber, pepper", "grind, mix, chill", "gazpacho")],
     "Cold soup from Moorish-era Andalusia before tomato arrived.",
     "Gazpacho is summer Andalusia — cold, bread-thick, olive oil shine."),
    ("Tortilla Española", "Spain", "Modern", 2, "eggs, tubers", "Egg",
     [s("potato, onion", "peel, heat", "cooked potato"),
      s("potato, egg", "mix, heat", "tortilla española")],
     "Potato omelette is Spain's most universal tapas bar staple.",
     "Tortilla debate is national sport — runny center or firm slice."),
    ("Jamón Ibérico", "Extremadura", "Medieval", 5, "meat", "Meat",
     [s("pork leg", "coat (salt), dry, age", "jamón ibérico")],
     "Acorn-fed pigs cured in mountain air for years.",
     "Jamón ibérico is Spanish luxury — melt fat, knife thin, ritual slice."),
    ("Churros", "Spain", "Medieval", 2, "grasses (wheat)", "Grain",
     [s("flour, water", "mix, heat", "churros")],
     "Fried dough from Spanish shepherds became chocolate-dip breakfast.",
     "Churros con chocolate is Madrid morning — hot oil, cinnamon sugar."),
])

add("Greek", [
    ("Moussaka", "Greece", "Modern", 3, "tubers, meat", "Combined",
     [s("eggplant", "peel, heat", "cooked eggplant"),
      s("lamb, tomato", "heat, layer", "meat layer"),
      s("layers, béchamel", "layer, heat", "moussaka")],
     "Layered eggplant casserole with Arab and Balkan influences.",
     "Moussaka is Greek Sunday — eggplant, cinnamon lamb, creamy top."),
    ("Souvlaki", "Greece", "Ancient", 2, "meat", "Meat",
     [s("lamb or pork", "strip, skewer, heat", "souvlaki")],
     "Skewered meat grilled over charcoal since antiquity.",
     "Souvlaki in pita is Athens street — tzatziki, onion, quick eat."),
    ("Spanakopita", "Greece", "Medieval", 3, "shoots, grasses", "Combined",
     [s("phyllo, spinach, feta", "layer, fill, heat", "spanakopita")],
     "Byzantine layered pastry with wild greens and cheese.",
     "Spanakopita is flaky green — spinach, feta, olive oil crackle."),
    ("Tzatziki", "Greece", "Ancient", 1, "roots (cucumber)", "Fermented",
     [s("yogurt, cucumber, garlic", "peel, grind, mix", "tzatziki")],
     "Yogurt-cucumber sauce cooling grilled meats in Mediterranean heat.",
     "Tzatziki is summer dip — garlic punch, cucumber crunch, yogurt cool."),
])

add("German", [
    ("Bratwurst", "Bavaria", "Medieval", 2, "meat", "Meat",
     [s("pork, spices", "grind, fill", "sausage"),
      s("sausage", "heat", "bratwurst")],
     "German sausage tradition spans hundreds of regional varieties.",
     "Bratwurst with mustard is beer garden baseline — snap, spice, bread."),
    ("Sauerkraut", "Germany", "Medieval", 2, "shoots (cabbage)", "Fermented",
     [s("cabbage, salt", "shred, ferment", "sauerkraut")],
     "Fermented cabbage preserved winter vegetables across Central Europe.",
     "Sauerkraut with pork is German winter — sour, soft, comforting."),
    ("Pretzel", "Bavaria", "Medieval", 2, "grasses (wheat)", "Grain",
     [s("flour", "mix, twist, coat (lye), heat", "pretzel")],
     "Monastery bread rewards shaped into prayer arms in southern Germany.",
     "Pretzel is beer hall salt — chewy knot, mustard dip, bakery warmth."),
    ("Sauerbraten", "Rhineland", "Medieval", 4, "meat", "Meat",
     [s("beef", "coat (vinegar marinade), simmer", "sauerbraten")],
     "Vinegar-marinated pot roast marinated for days before slow cooking.",
     "Sauerbraten is Sunday Rhineland — sweet-sour gravy, gingerbread depth."),
])

add("British", [
    ("Fish and Chips", "England", "Industrial", 2, "fish", "Seafood",
     [s("fish", "clean, coat", "battered fish"),
      s("potato", "peel, heat", "chips"),
      s("fish, chips", "layer", "fish and chips")],
     "Industrial-era fried fish with potato became working-class staple.",
     "Fish and chips is seaside wrap — vinegar splash, newspaper memory."),
    ("Shepherd's Pie", "Britain", "Industrial", 2, "meat, tubers", "Combined",
     [s("lamb, vegetables", "heat, mix", "filling"),
      s("potato", "boil, mash", "mashed top"),
      s("filling, potato", "layer, heat", "shepherd's pie")],
     "Cottage pie uses beef; shepherd's uses lamb in potato-topped casserole.",
     "Shepherd's pie is pub comfort — meat gravy, mashed blanket."),
    ("Yorkshire Pudding", "Yorkshire", "Medieval", 2, "grasses (wheat), eggs", "Combined",
     [s("flour, egg, milk", "mix, heat", "yorkshire pudding")],
     "Batter puddings caught roast drippings in northern England ovens.",
     "Yorkshire pud is Sunday roast vessel — gravy pool, crispy well."),
    ("Full English Breakfast", "England", "Modern", 2, "eggs, meat", "Combined",
     [s("egg, bacon, sausage, beans, tomato", "heat, layer", "full English")],
     "Post-war café culture codified hearty morning plate.",
     "Full English is fry-up ritual — plate wide, tea strong, day begun."),
])

add("Scandinavian", [
    ("Gravlax", "Nordic", "Medieval", 3, "fish", "Seafood",
     [s("salmon", "clean, coat (salt dill), ferment", "gravlax")],
     "Buried cured salmon from Viking preservation methods.",
     "Gravlax with mustard sauce is Nordic elegance — silky, dill, cold."),
    ("Swedish Meatballs", "Sweden", "Modern", 2, "meat", "Meat",
     [s("beef, pork", "grind, mix, form, heat", "meatballs")],
     "Small meatballs with cream gravy from Swedish home kitchens.",
     "Köttbullar with lingonberry is IKEA and tradition — cozy, round, gravy."),
    ("Smørrebrød", "Denmark", "Modern", 2, "grasses (rye)", "Combined",
     [s("rye bread", "slice, layer", "smørrebrød base"),
      s("herring, egg, toppings", "layer", "open sandwich")],
     "Open-faced rye sandwiches artfully topped for Danish lunch.",
     "Smørrebrød is edible composition — herring, egg, dill, rye base."),
    ("Lutefisk", "Norway", "Medieval", 5, "fish", "Seafood",
     [s("dried cod", "soak (lye), boil", "lutefisk")],
     "Lye-soaked preserved cod is Christmas tradition in Norway and Minnesota.",
     "Lutefisk is acquired heritage — gelatinous, buttered, ancestral ritual."),
])

add("Eastern European", [
    ("Pierogi", "Poland", "Medieval", 3, "grasses (wheat)", "Combined",
     [s("flour", "mix, wrap", "dough"),
      s("potato, cheese", "fill", "pierogi"),
      s("pierogi", "boil, heat", "fried pierogi")],
     "Stuffed dumplings spread from Central Asia through Slavic kitchens.",
     "Pierogi is Polish comfort — potato fill, butter onion, grandma hands."),
    ("Borscht", "Ukraine", "Medieval", 2, "roots (beet)", "Combined",
     [s("beet, cabbage, stock", "peel, boil, mix", "borscht")],
     "Beet soup varies red hot or cold across Eastern Europe.",
     "Borscht with sour cream is Slavic winter — ruby bowl, dill float."),
    ("Goulash", "Hungary", "Medieval", 3, "meat", "Meat",
     [s("beef, paprika, onion", "heat, simmer", "goulash")],
     "Hungarian herdsmen's paprika stew became Habsburg empire dish.",
     "Goulash is paprika red — herdsman pot, bread dip, warming spice."),
    ("Blini", "Russia", "Medieval", 2, "grasses (wheat)", "Grain",
     [s("flour, yeast", "ferment, heat", "blini")],
     "Yeasted pancakes served with caviar and sour cream at celebrations.",
     "Blini with caviar is Maslenitsa luxury — thin stack, butter gloss."),
    ("Pelmeni", "Siberia", "Medieval", 3, "grasses (wheat), meat", "Combined",
     [s("dough", "mix, wrap", "wrappers"),
      s("minced meat", "fill", "pelmeni"),
      s("pelmeni", "boil", "boiled dumplings")],
     "Frozen dumplings carried by Siberian hunters and traders.",
     "Pelmeni in butter is Siberian soul — small parcels, sour cream, cold night."),
])

# ── AFRICA ──────────────────────────────────────────────────────────────────
add("West African", [
    ("Jollof Rice", "Nigeria/Ghana", "Modern", 3, "grasses (rice)", "Combined",
     [s("rice, tomato, pepper", "heat, mix, layer", "jollof rice")],
     "Tomato-stewed rice spread from Wolof empire across West Africa.",
     "Jollof rivalry is Nigeria vs Ghana — smoky bottom, party essential."),
    ("Egusi Soup", "Nigeria", "Medieval", 3, "seeds (melon)", "Combined",
     [s("melon seeds", "grind", "egusi paste"),
      s("paste, greens, meat", "heat, mix", "egusi soup")],
     "Ground melon seed thickens stew across Igbo and Yoruba kitchens.",
     "Egusi with fufu is Nigerian Sunday — nutty, rich, communal dip."),
    ("Suya", "Nigeria", "Modern", 2, "meat", "Meat",
     [s("beef", "strip, coat (yaji spice), heat", "suya")],
     "Hausa spice-rubbed grilled skewers sold at night markets.",
     "Suya is street spice cloud — peanut chili rub, onion wrap, night eat."),
    ("Thieboudienne", "Senegal", "Modern", 3, "fish, grasses", "Combined",
     [s("fish, rice, vegetables", "heat, layer, simmer", "thieboudienne")],
     "Senegal's national dish — fish and rice with fermented tamarind.",
     "Thieboudienne is Dakar feast — broken rice, fish, stuffed pepper."),
    ("Fufu", "West Africa", "Ancient", 2, "tubers", "Tuber",
     [s("cassava or plantain", "boil, pound", "fufu")],
     "Pounded starch accompaniment dipped into soups across West Africa.",
     "Fufu is finger food architecture — stretch, dip, swallow, repeat."),
])

add("Ethiopian", [
    ("Injera", "Ethiopia", "Ancient", 3, "seeds (teff)", "Grain",
     [s("teff flour", "ferment, mix, heat", "injera")],
     "Fermented teff flatbread is plate and utensil in Ethiopian dining.",
     "Injera under wat is edible table — sour sponge, shared tear."),
    ("Doro Wat", "Ethiopia", "Medieval", 4, "poultry", "Meat",
     [s("chicken, berbere, onion", "heat, simmer", "doro wat")],
     "Spiced chicken stew slow-cooked for celebrations and fasting breaks.",
     "Doro wat with egg is Ethiopian feast — berbere fire, communal injera."),
    ("Shiro Wat", "Ethiopia", "Medieval", 2, "seeds (legumes)", "Combined",
     [s("ground legumes, spices", "mix, simmer", "shiro wat")],
     "Chickpea or bean flour stew for fasting and everyday meals.",
     "Shiro is fasting comfort — smooth, spiced, vegan protein."),
])

add("North African (Maghreb)", [
    ("Shakshuka", "Tunisia", "Modern", 2, "eggs, fruits (tomato)", "Egg",
     [s("tomato, pepper, egg", "heat, mix, fill", "shakshuka")],
     "Eggs poached in spiced tomato sauce spread from Maghreb globally.",
     "Shakshuka is brunch pan — bread dip, chili heat, shared skillet."),
    ("Méchoui", "Morocco", "Ancient", 4, "meat", "Meat",
     [s("whole lamb", "coat, heat", "méchoui")],
     "Pit-roasted whole lamb for Berber celebrations and feasts.",
     "Méchoui is desert gathering — whole animal, hand tear, communal."),
])

add("Southern African", [
    ("Bobotie", "South Africa", "Modern", 3, "meat", "Meat",
     [s("minced meat, spices, egg", "mix, layer, heat", "bobotie")],
     "Cape Malay spiced baked mince with egg topping from colonial fusion.",
     "Bobotie is Cape Town sweet-savory — curry, apricot, raisin, egg cap."),
    ("Pap", "Southern Africa", "Ancient", 1, "grasses (maize)", "Grain",
     [s("maize meal", "boil, mix", "pap")],
     "Maize porridge staple across southern Africa with braai culture.",
     "Pap with wors is braai baseline — stiff porridge, sausage, sauce."),
])

# ── AMERICAS ────────────────────────────────────────────────────────────────
add("Mexican", [
    ("Tacos al Pastor", "Mexico City", "Modern", 2, "meat", "Meat",
     [s("marinated pork", "skewer, heat", "al pastor"),
      s("meat, tortilla, pineapple", "wrap, layer", "tacos al pastor")],
     "Lebanese shawarma spits met Mexican adobo and pineapple.",
     "Al pastor is trompo spin — char edge, pineapple sweet, tortilla."),
    ("Tamales", "Mexico", "Ancient", 4, "grasses (maize)", "Combined",
     [s("maize", "grind, mix", "masa"),
      s("masa, filling", "wrap, steam", "tamales")],
     "Aztec tamalli steamed in corn husks for millennia.",
     "Tamales are holiday labor — family wrap, steam hum, masa comfort."),
    ("Mole Poblano", "Puebla", "Medieval", 5, "mixed", "Combined",
     [s("chili, chocolate, spices", "grind, mix, simmer", "mole"),
      s("mole, chicken", "coat, heat", "mole poblano")],
     "Complex sauce with dozens of ingredients from Puebla convent tradition.",
     "Mole is Mexico in a bowl — chocolate depth, chili stack, celebration."),
    ("Pozole", "Jalisco", "Ancient", 3, "grasses (maize), meat", "Combined",
     [s("hominy, pork", "boil, simmer", "pozole")],
     "Pre-Columbian hominy stew served red, white, or green by region.",
     "Pozole is fiesta bowl — radish crunch, lime, hominy chew."),
    ("Guacamole", "Mexico", "Ancient", 1, "fruits (avocado)", "Fruit",
     [s("avocado, lime, onion", "peel, crush, mix", "guacamole")],
     "Aztec ahuacamolli mashed with molcajete before colonization.",
     "Guacamole is table start — lime bright, tortilla chip shovel."),
    ("Enchiladas", "Mexico", "Medieval", 3, "grasses (maize)", "Combined",
     [s("tortilla, filling", "fill, wrap", "rolled tortillas"),
      s("rolls, chili sauce", "coat, heat", "enchiladas")],
     "Corn tortillas rolled around filling and bathed in chili sauce.",
     "Enchiladas are saucy comfort — chili bath, cheese melt, fork soft."),
    ("Chiles Rellenos", "Mexico", "Modern", 3, "fruits (pepper)", "Combined",
     [s("poblano pepper, cheese", "fill, coat, heat", "chiles rellenos")],
     "Stuffed roasted peppers battered and fried in Puebla style.",
     "Chiles rellenos are poblano surprise — cheese pull, crispy coat."),
])

add("Peruvian", [
    ("Ceviche", "Peru", "Ancient", 2, "fish", "Seafood",
     [s("fish, lime, chili", "clean, mix, ferment", "ceviche")],
     "Coastal Peruvians cured fish in chicha and lime before Inca empire.",
     "Ceviche is Pacific acid — lime cure, ají kick, sweet potato side."),
    ("Lomo Saltado", "Peru", "Modern", 2, "meat, tubers", "Combined",
     [s("beef, potato, tomato", "heat, mix", "lomo saltado")],
     "Chinese stir-fry technique met Peruvian ingredients in chifa fusion.",
     "Lomo saltado is wok on rice — soy, tomato, french fry top."),
    ("Anticuchos", "Peru", "Ancient", 2, "meat", "Meat",
     [s("beef heart", "clean, skewer, coat, heat", "anticuchos")],
     "Pre-Columbian grilled organ skewers with ají marinade.",
     "Anticuchos are street charcoal — heart chew, vinegar ají, night market."),
    ("Causa", "Peru", "Modern", 2, "tubers", "Tuber",
     [s("potato, lime, ají", "boil, mash, layer, fill", "causa")],
     "Layered potato terrine with chicken or tuna filling.",
     "Causa is cool potato layers — yellow mash, olive egg garnish."),
])

add("Brazilian", [
    ("Feijoada", "Brazil", "Medieval", 4, "seeds, meat", "Combined",
     [s("black beans, pork", "soak, boil, simmer", "feijoada")],
     "Portuguese bean stew enriched with enslaved African kitchen wisdom.",
     "Feijoada is Saturday slow — black beans, farofa, orange slice."),
    ("Pão de Queijo", "Minas Gerais", "Modern", 2, "tubers (tapioca)", "Combined",
     [s("tapioca flour, cheese", "mix, heat", "pão de queijo")],
     "Cheese bread from cassava starch in Minas Gerais coffee region.",
     "Pão de queijo is café da manhã — chewy, cheesy, warm ball."),
    ("Moqueca", "Bahia", "Medieval", 3, "fish", "Seafood",
     [s("fish, coconut, dendê oil", "clean, heat, simmer", "moqueca")],
     "Afro-Brazilian fish stew with palm oil and coconut milk.",
     "Moqueca is Bahia sunshine — dendê red, coconut silk, fish flake."),
    ("Brigadeiro", "Brazil", "Modern", 1, "seeds (cocoa)", "Fruit",
     [s("condensed milk, cocoa, butter", "mix, heat", "brigadeiro")],
     "Fudge truffle born from wartime condensed milk and cocoa surplus.",
     "Brigadeiro is birthday party — chocolate ball, sprinkles, childhood."),
])

add("Argentinian", [
    ("Asado", "Pampas", "Modern", 3, "meat", "Meat",
     [s("beef cuts", "coat (salt), heat", "asado")],
     "Gaucho open-fire grilling on parrilla defines Argentine identity.",
     "Asado is Sunday fire — chimichurri, malbec, hours of meat."),
    ("Empanadas", "Argentina", "Medieval", 3, "grasses (wheat)", "Combined",
     [s("dough", "mix, fill, wrap, heat", "empanadas")],
     "Galician empanada adapted with criollo fillings across provinces.",
     "Empanadas are hand pie debate — baked vs fried, beef vs ham."),
    ("Dulce de Leche", "Argentina", "Industrial", 2, "milk", "Fermented",
     [s("milk, sugar", "heat, mix", "dulce de leche")],
     "Caramelized milk spread became national obsession on everything.",
     "Dulce de leche is Argentina sweet — alfajor glue, toast, memory."),
])

add("Caribbean", [
    ("Jerk Chicken", "Jamaica", "Modern", 3, "poultry", "Meat",
     [s("chicken", "coat (jerk spice), smoke, heat", "jerk chicken")],
     "Maroon escaped slaves developed pimento wood smoke and scotch bonnet rub.",
     "Jerk is Jamaica fire — allspice smoke, scotch bonnet, roadside drum."),
    ("Rice and Peas", "Jamaica", "Modern", 2, "grasses (rice), seeds", "Combined",
     [s("rice, kidney beans, coconut", "boil, steam", "rice and peas")],
     "Sunday accompaniment to jerk and curry across Caribbean.",
     "Rice and peas is Sunday pot — coconut milk, thyme, kidney bean."),
    ("Callaloo", "Trinidad", "Modern", 2, "shoots", "Leaf/Shoot",
     [s("dasheen leaves, okra", "strip, boil, mix", "callaloo")],
     "West African greens stew adapted in Trinidad and Tobago.",
     "Callaloo is island green — coconut, crab, pepper pot."),
    ("Roti", "Trinidad", "Modern", 2, "grasses (wheat)", "Grain",
     [s("flour", "mix, heat", "roti"),
      s("roti, curry", "wrap, fill", "roti wrap")],
     "Indian indentured labor brought flatbread that met Caribbean curry.",
     "Roti with curry is Trini lunch — tear, scoop, pepper burn."),
])

add("Central American", [
    ("Pupusas", "El Salvador", "Ancient", 2, "grasses (maize)", "Combined",
     [s("maize masa", "mix, fill, heat", "pupusas")],
     "Stuffed corn cakes from Pipil indigenous tradition.",
     "Pupusas with curtido is Salvadoran heart — cheese pocket, cabbage pickle."),
    ("Gallo Pinto", "Costa Rica/Nicaragua", "Modern", 1, "grasses (rice), seeds", "Combined",
     [s("rice, black beans", "heat, mix", "gallo pinto")],
     "Rice and beans breakfast staple across Central America.",
     "Gallo pinto is morning fuel — Lizano sauce, egg side, national pride."),
])

add("USA", [
    ("Clam Chowder", "New England", "Industrial", 2, "shellfish", "Seafood",
     [s("clams, potato, cream", "clean, boil, mix", "clam chowder")],
     "Creamy soup from Northeast fishing villages and canneries.",
     "New England chowder is bread bowl — clam brine, potato chunk, foggy coast."),
    ("BBQ Brisket", "Texas", "Modern", 4, "meat", "Meat",
     [s("beef brisket", "coat (rub), smoke, heat", "BBQ brisket")],
     "Central Texas post-oak smoke for twelve-plus hours.",
     "Brisket is Texas religion — bark, smoke ring, white bread, pickle."),
    ("Gumbo", "Louisiana", "Medieval", 4, "mixed", "Combined",
     [s("roux, okra, seafood or sausage", "heat, mix, simmer", "gumbo")],
     "Louisiana stew blending French, African, and Choctaw traditions.",
     "Gumbo is Louisiana bowl — roux dark, file powder, rice under."),
    ("Jambalaya", "Louisiana", "Modern", 3, "grasses (rice), meat", "Combined",
     [s("rice, sausage, shrimp", "heat, mix, layer", "jambalaya")],
     "One-pot rice dish cousin to paella and jollof in Creole kitchens.",
     "Jambalaya is Cajun party — andouille, shrimp, one pot feeds all."),
    ("Mac and Cheese", "USA", "Industrial", 2, "grasses (wheat), seeds", "Combined",
     [s("pasta, cheese", "boil, mix, heat", "mac and cheese")],
     "Jefferson-era pasta met American cheddar to become comfort classic.",
     "Mac and cheese is American childhood — orange, creamy, oven crust."),
    ("Hamburger", "USA", "Modern", 2, "meat, grasses", "Combined",
     [s("beef", "grind, form, heat", "patty"),
      s("patty, bun, toppings", "layer", "hamburger")],
     "German Hamburg steak on bun became global fast food icon.",
     "Hamburger is American export — sesame bun, pickle, drive-through."),
])

add("Polynesian", [
    ("Poke", "Hawaii", "Ancient", 2, "fish", "Seafood",
     [s("tuna", "clean, cube, mix", "poke")],
     "Hawaiian raw fish salad with sea salt and limu seaweed.",
     "Poke bowl is Pacific fresh — soy fusion, ahi cube, rice base."),
    ("Hangi", "Māori", "Ancient", 4, "mixed", "Combined",
     [s("meat, tubers", "wrap, heat (earth oven)", "hangi")],
     "Earth oven steaming food buried with heated stones.",
     "Hangi is Aotearoa gathering — earth steam, kumara, communal unwrap."),
    ("Poi", "Hawaii", "Ancient", 1, "tubers (taro)", "Tuber",
     [s("taro root", "peel, pound, ferment", "poi")],
     "Pounded taro paste fermented to tangy staple in Hawaiian diet.",
     "Poi is finger-dip tradition — mild sour, luau bowl, ancestral starch."),
    ("Lomi Lomi Salmon", "Hawaii", "Modern", 2, "fish", "Seafood",
     [s("salmon, tomato, onion", "clean, mix", "lomi lomi salmon")],
     "Salted salmon salad mixed by hand at Hawaiian gatherings.",
     "Lomi lomi is luau side — cool, salty, tomato bright."),
])

add("Cambodian", [
    ("Fish Amok", "Cambodia", "Medieval", 3, "fish", "Seafood",
     [s("fish, coconut, kroeung", "grind, mix, steam", "fish amok")],
     "Steamed fish custard in banana leaf from Khmer royal kitchens.",
     "Amok is Cambodia silk — coconut curry, lemongrass, leaf parcel."),
    ("Lok Lak", "Cambodia", "Modern", 2, "meat", "Meat",
     [s("beef", "coat, heat", "lok lak")],
     "Vietnamese-influenced pepper beef with lime dipping sauce.",
     "Lok lak is Phnom Penh plate — pepper, lime, rice underneath."),
    ("Nom Banh Chok", "Cambodia", "Ancient", 2, "grasses (rice)", "Grain",
     [s("rice noodles, fish gravy", "ferment, boil, layer", "nom banh chok")],
     "Fermented fish gravy over fresh rice noodles for breakfast.",
     "Nom banh chok is morning market — herbs, cucumber, cool noodles."),
])

add("Burmese", [
    ("Mohinga", "Myanmar", "Modern", 3, "fish, grasses", "Combined",
     [s("fish, rice noodles, chickpea", "boil, grind, layer", "mohinga")],
     "National breakfast noodle soup with lemongrass and banana stem.",
     "Mohinga is Yangon dawn — fish broth, crunch toppings, street steam."),
    ("Laphet Thoke", "Myanmar", "Ancient", 2, "fermented", "Fermented",
     [s("fermented tea leaves, nuts", "mix", "tea leaf salad")],
     "Fermented tea leaf salad is unique Burmese social snack.",
     "Laphet thoke is bitter-tea party — crunch, sesame, shared plate."),
    ("Ohn No Khao Swè", "Myanmar", "Modern", 2, "grasses (wheat)", "Combined",
     [s("wheat noodles, coconut chicken", "boil, layer", "ohn no khao swe")],
     "Coconut chicken noodle soup from Burmese Indian community.",
     "Ohn no khao swe is comfort bowl — coconut silk, egg noodle, chili oil."),
])

add("Portuguese", [
    ("Bacalhau à Brás", "Portugal", "Medieval", 3, "fish", "Seafood",
     [s("salt cod", "soak, shred, heat, mix", "bacalhau à brás")],
     "Shredded salt cod with potato and egg from Lisbon taverns.",
     "Bacalhau is Portugal obsession — 365 recipes, salt cod king."),
    ("Pastel de Nata", "Lisbon", "Modern", 3, "grasses (wheat), eggs", "Combined",
     [s("pastry, custard", "mix, fill, heat", "pastel de nata")],
     "Creamy egg tart from Belém monastery since 1837.",
     "Pastel de nata is Lisbon queue — cinnamon dust, caramel blister."),
    ("Caldo Verde", "Minho", "Medieval", 1, "shoots, tubers", "Combined",
     [s("kale, potato, chorizo", "chop, boil, mix", "caldo verde")],
     "Green soup from northern Portugal with couve and sausage.",
     "Caldo verde is festival night — kale ribbon, smoky sausage."),
])

add("Irish", [
    ("Irish Stew", "Ireland", "Medieval", 2, "meat, tubers", "Combined",
     [s("lamb, potato, onion", "chop, boil, simmer", "Irish stew")],
     "One-pot lamb and potato sustained rural Ireland for centuries.",
     "Irish stew is pub hearth — soft potato, lamb fall, bread soak."),
    ("Soda Bread", "Ireland", "Industrial", 1, "grasses (wheat)", "Grain",
     [s("flour, buttermilk, soda", "mix, heat", "soda bread")],
     "Baking soda leavened bread when yeast was scarce in famine era.",
     "Soda bread is cross-cut tradition — dense crumb, butter melt."),
    ("Colcannon", "Ireland", "Medieval", 1, "tubers, shoots", "Tuber",
     [s("potato, cabbage", "boil, mash, mix", "colcannon")],
     "Mashed potato with kale or cabbage for Halloween and harvest.",
     "Colcannon hides charm in bowl — butter well, fortune coin."),
    ("Boxty", "Ireland", "Medieval", 2, "tubers", "Tuber",
     [s("potato, flour", "grate, mix, heat", "boxty")],
     "Grated potato pancake from northern Irish counties.",
     "Boxty rhyme promises marriage — pan fry, griddle crisp."),
])

add("Cuban", [
    ("Ropa Vieja", "Cuba", "Modern", 2, "meat", "Meat",
     [s("beef", "boil, shred, simmer", "ropa vieja")],
     "Shredded beef in tomato-sofrito from Canary Island settlers.",
     "Ropa vieja is Cuban soul — shredded threads, rice, black beans."),
    ("Cuban Sandwich", "Tampa/Havana", "Modern", 2, "grasses (wheat), meat", "Combined",
     [s("bread, pork, ham, pickle, cheese", "layer, press, heat", "Cuban sandwich")],
     "Pressed sandwich with mojo pork migrated between Cuba and Florida.",
     "Cuban sandwich is crunch press — pickle acid, pork, Swiss melt."),
    ("Moros y Cristianos", "Cuba", "Medieval", 2, "grasses (rice), seeds", "Combined",
     [s("rice, black beans", "heat, mix", "moros y cristianos")],
     "Black beans and rice named for Moor and Christian history.",
     "Moros y cristianos is daily Cuba — vinegar onion, oregano, staple."),
])

add("Colombian", [
    ("Bandeja Paisa", "Antioquia", "Modern", 3, "mixed", "Combined",
     [s("rice, beans, meat, egg, plantain", "heat, layer", "bandeja paisa")],
     "Mountain platter feeding Andean workers with protein and starch.",
     "Bandeja paisa is Colombia mountain — chicharrón, avocado, arepa."),
    ("Arepas", "Colombia/Venezuela", "Ancient", 2, "grasses (maize)", "Grain",
     [s("maize meal", "mix, heat", "arepas")],
     "Pre-Columbian corn cakes grilled across northern South America.",
     "Arepas are daily bread — pocket, cheese fill, morning butter."),
    ("Ajiaco", "Bogotá", "Modern", 2, "tubers, poultry", "Combined",
     [s("potato varieties, chicken, corn", "boil, mix", "ajiaco")],
     "Bogotá highland soup with three potato types and guascas herb.",
     "Ajiaco is Andean fog — capers, cream, multiple potato silk."),
])

add("Chilean", [
    ("Empanada de Pino", "Chile", "Medieval", 3, "grasses (wheat), meat", "Combined",
     [s("dough, beef, onion, olive, egg", "fill, wrap, heat", "empanada de pino")],
     "Baked empanada with olive and hard-boiled egg for Fiestas Patrias.",
     "Empanada de pino is Chile September — oven bake, pino filling."),
    ("Pastel de Choclo", "Chile", "Modern", 3, "grasses (maize), meat", "Combined",
     [s("corn, beef, chicken", "grind, layer, heat", "pastel de choclo")],
     "Corn custard topping over meat pie in clay dish.",
     "Pastel de choclo is summer corn — sweet top, savory base."),
    ("Cazuela", "Chile", "Medieval", 2, "mixed", "Combined",
     [s("meat, corn, potato, pumpkin", "boil, layer", "cazuela")],
     "Home-style broth with seasonal vegetables across Chile.",
     "Cazuela is grandmother pot — pumpkin chunk, corn on cob."),
])

add("Venezuelan", [
    ("Pabellón Criollo", "Venezuela", "Modern", 2, "grasses (rice), seeds, meat", "Combined",
     [s("rice, black beans, shredded beef, plantain", "heat, layer", "pabellón")],
     "National plate with colors echoing flag — beans, rice, meat, plantain.",
     "Pabellón is Venezuela lunch — sweet plantain, salty meat, avocado."),
    ("Hallacas", "Venezuela", "Medieval", 4, "grasses (maize)", "Combined",
     [s("maize dough, stewed filling", "wrap, boil", "hallacas")],
     "Christmas tamale cousin wrapped in banana leaves with complex stew.",
     "Hallacas are December labor — family assembly, leaf wrap, holiday."),
])

add("Austrian", [
    ("Wiener Schnitzel", "Vienna", "Modern", 3, "meat", "Meat",
     [s("veal cutlet", "pound, coat, heat", "wiener schnitzel")],
     "Breaded veal cutlet pounded thin in Viennese imperial tradition.",
     "Wiener schnitzel is golden veil — lemon squeeze, potato salad side."),
    ("Apfelstrudel", "Vienna", "Medieval", 4, "fruits (apple), grasses", "Combined",
     [s("apple, phyllo", "peel, fill, layer, heat", "apfelstrudel")],
     "Paper-thin strudel dough stretched over apple filling in Habsburg cafes.",
     "Apfelstrudel is café steam — cinnamon apple, powdered sugar snow."),
    ("Tafelspitz", "Vienna", "Modern", 3, "meat", "Meat",
     [s("beef, root vegetables", "boil, simmer", "tafelspitz")],
     "Boiled beef dinner favored by Emperor Franz Joseph.",
     "Tafelspitz is imperial boil — horseradish, apple-horseradish, broth."),
])

add("Swiss", [
    ("Fondue", "Switzerland", "Medieval", 2, "seeds (cheese)", "Combined",
     [s("cheese, wine", "heat, mix", "fondue")],
     "Melted cheese communal pot from Alpine cowherd winter survival.",
     "Fondue is ski chalet — bread dip, wine swirl, shared fork."),
    ("Rösti", "Switzerland", "Modern", 1, "tubers", "Tuber",
     [s("potato", "peel, grate, heat", "rösti")],
     "Crispy grated potato pancake from German-speaking Swiss cantons.",
     "Rösti is crispy base — golden disk, egg on top, Alpine breakfast."),
    ("Zürcher Geschnetzeltes", "Zurich", "Modern", 2, "meat", "Meat",
     [s("veal, mushrooms, cream", "strip, heat, mix", "zürcher geschnetzeltes")],
     "Creamy veal strips with mushrooms in Zurich wine sauce.",
     "Geschnetzeltes over rösti is Zurich plate — cream, mushroom, veal."),
])

add("Belgian", [
    ("Moules-Frites", "Belgium", "Modern", 2, "shellfish, tubers", "Combined",
     [s("mussels, wine, herbs", "clean, heat", "mussels"),
      s("potato", "peel, heat", "frites")],
     "North Sea mussels with twice-fried potatoes in brasseries.",
     "Moules-frites is Belgian brasserie — empty shell tower, mayo dip."),
    ("Belgian Waffles", "Belgium", "Industrial", 2, "grasses (wheat), eggs", "Combined",
     [s("flour, egg, pearl sugar", "mix, heat", "liège waffle")],
     "Pearl sugar caramelizes in dense Liège waffle tradition.",
     "Belgian waffles are street fair — sugar crunch, no syrup needed."),
    ("Waterzooi", "Ghent", "Medieval", 3, "poultry", "Meat",
     [s("chicken, leeks, cream", "boil, simmer", "waterzooi")],
     "Creamy chicken stew from medieval Ghent guild kitchens.",
     "Waterzooi is Flemish comfort — egg yolk liaison, gentle poach."),
])

add("Dutch", [
    ("Stroopwafel", "Netherlands", "Industrial", 2, "grasses (wheat)", "Grain",
     [s("waffle batter, caramel syrup", "heat, layer", "stroopwafel")],
     "Syrup sandwich waffle invented in Gouda bakeries circa 1784.",
     "Stroopwafel on coffee cup — steam softens caramel middle."),
    ("Bitterballen", "Netherlands", "Modern", 3, "meat, grasses", "Combined",
     [s("ragout, breadcrumbs", "mix, coat, heat", "bitterballen")],
     "Deep-fried beef ragout balls served with mustard at borrel hour.",
     "Bitterballen are pub crunch — hot center, cold beer, borrel ritual."),
    ("Erwtensoep", "Netherlands", "Medieval", 2, "seeds (peas)", "Combined",
     [s("split peas, pork, vegetables", "boil, simmer", "erwtensoep")],
     "Thick pea soup so dense a spoon stands — winter skating food.",
     "Snert with rye bread is Dutch winter — smoked sausage, pea thick."),
])

add("Mongolian", [
    ("Buuz", "Mongolia", "Ancient", 3, "grasses (wheat), meat", "Combined",
     [s("flour dough", "mix, wrap", "dumpling skins"),
      s("minced mutton", "fill, steam", "buuz")],
     "Steamed mutton dumplings for Tsagaan Sar lunar new year.",
     "Buuz are nomad parcels — steam batch, dip in tea, winter fuel."),
    ("Khorkhog", "Mongolia", "Ancient", 4, "meat, tubers", "Combined",
     [s("lamb, stones, vegetables", "layer, heat (sealed pot)", "khorkhog")],
     "Hot stones cook meat and vegetables in sealed milk can outdoors.",
     "Khorkhog is steppe feast — stone crackle, communal tear, outdoor fire."),
    ("Boodog", "Mongolia", "Ancient", 5, "meat", "Meat",
     [s("whole goat or marmot", "fill (hot stones), heat", "boodog")],
     "Whole animal cooked from inside with heated stones in hide.",
     "Boodog is nomad spectacle — primal roast, celebration, steppe skill."),
])

add("Tibetan", [
    ("Momo", "Tibet", "Medieval", 3, "grasses (wheat), meat", "Combined",
     [s("dough", "mix, wrap", "wrappers"),
      s("meat or vegetables", "fill, steam", "momo")],
     "Steamed dumplings from Himalayan trade with Nepal and China.",
     "Momo with chili sauce is mountain comfort — pleat, steam, dip."),
    ("Tsampa", "Tibet", "Ancient", 1, "grasses (barley)", "Grain",
     [s("roasted barley flour", "grind, mix (with tea)", "tsampa")],
     "Roasted barley flour mixed with butter tea sustains plateau life.",
     "Tsampa is pilgrim fuel — finger mix, butter tea, altitude staple."),
    ("Thenthuk", "Tibet", "Medieval", 2, "grasses (wheat)", "Grain",
     [s("flour, meat, vegetables", "pull, boil", "thenthuk")],
     "Hand-pulled noodle soup warming high-altitude monasteries.",
     "Thenthuk is noodle pull — irregular strips, broth, winter monastery."),
])

add("Bengali", [
    ("Macher Jhol", "West Bengal", "Modern", 2, "fish", "Seafood",
     [s("fish, mustard, turmeric", "clean, heat, mix", "macher jhol")],
     "Light fish curry with mustard oil defines Bengali daily cooking.",
     "Macher jhol on rice is Bengal lunch — mustard sting, river fish."),
    ("Roshogolla", "West Bengal", "Industrial", 3, "grasses (milk solids)", "Fruit",
     [s("chenna, sugar syrup", "form, boil", "roshogolla")],
     "Spongy cheese balls in syrup from Kolkata sweet shops.",
     "Roshogolla is Bengal sweetness — syrup squeeze, festival gift."),
    ("Shorshe Ilish", "Bengal", "Modern", 3, "fish", "Seafood",
     [s("hilsa fish, mustard paste", "coat, steam", "shorshe ilish")],
     "Monsoon hilsa in mustard sauce is Bengali cultural obsession.",
     "Ilish in mustard is monsoon poetry — bone navigate, mustard fire."),
    ("Luchi with Aloor Dom", "Bengal", "Modern", 2, "grasses (wheat), tubers", "Combined",
     [s("flour", "mix, heat", "luchi"),
      s("potato, spices", "heat, mix", "aloor dom")],
     "Puffy fried bread with spiced potato curry for breakfast.",
     "Luchi-aloor dom is Sunday morning — puff bread, potato warmth."),
])

add("Nepalese", [
    ("Dal Bhat", "Nepal", "Ancient", 1, "seeds, grasses", "Combined",
     [s("lentils", "boil", "dal"),
      s("rice", "steam", "bhat"),
      s("dal, bhat, vegetables", "layer", "dal bhat")],
     "Twice-daily lentil and rice sustains Himalayan farmers and trekkers.",
     "Dal bhat power 24 hour — refill until you leave the table."),
    ("Momo (Nepalese)", "Kathmandu", "Modern", 3, "grasses (wheat)", "Combined",
     [s("dough, buffalo or vegetable", "fill, steam", "Nepalese momo")],
     "Tibetan dumplings adopted as Nepal's favorite street food.",
     "Momo with achar is Kathmandu alley — c-fold pleat, chili dip."),
    ("Sel Roti", "Nepal", "Medieval", 3, "grasses (rice)", "Grain",
     [s("rice flour, sugar", "mix, ferment, heat", "sel roti")],
     "Ring-shaped rice bread fried for Tihar and weddings.",
     "Sel roti is festival ring — crispy outside, soft inside, cardamom."),
])

add("Egyptian", [
    ("Mahshi", "Egypt", "Medieval", 3, "shoots, grasses", "Combined",
     [s("grape leaves or vegetables", "fill, wrap, heat", "mahshi")],
     "Stuffed vegetables and leaves with rice filling across Levant and Egypt.",
     "Mahshi is family roll — vine leaf, rice, lemon, communal pot."),
    ("Molokhia", "Egypt", "Ancient", 2, "shoots", "Leaf/Shoot",
     [s("jute leaves, garlic, coriander", "strip, boil, mix", "molokhia")],
     "Slimy green soup from jute leaves loved since Pharaonic times.",
     "Molokhia with rabbit is Egyptian home — garlic crackle, viscous green."),
])

add("Southern African", [
    ("Boerewors", "South Africa", "Modern", 2, "meat", "Meat",
     [s("beef, spices", "grind, fill", "boerewors"),
      s("sausage", "heat", "grilled boerewors")],
     "Coiled farmhouse sausage essential to South African braai.",
     "Boerewors on braai is weekend — coriander, clove, coil turn."),
    ("Bunny Chow", "Durban", "Modern", 2, "grasses (wheat), meat", "Combined",
     [s("bread loaf", "hollow, fill", "bunny chow"),
      s("curry", "heat, fill", "curry bunny")],
     "Indian South African curry served in hollowed bread loaf.",
     "Bunny chow is Durban street — tear bread, scoop curry, no plate."),
    ("Potjiekos", "South Africa", "Modern", 3, "meat", "Meat",
     [s("meat, vegetables", "layer, heat (cast pot)", "potjiekos")],
     "Cast-iron pot layered stew cooked slowly over outdoor coals.",
     "Potjiekos is campfire layers — no stir, three-hour patience."),
])

add("Central American", [
    ("Tacos (Street)", "Mexico/Central America", "Ancient", 1, "grasses (maize)", "Combined",
     [s("maize", "grind, mix, heat", "tortilla"),
      s("tortilla, filling", "fill, layer", "taco")],
     "Corn tortilla predates colonization across Mesoamerica.",
     "Taco is hand food universal — fold, squeeze lime, street stand."),
    ("Ceviche (Central American)", "El Salvador", "Ancient", 2, "shellfish", "Seafood",
     [s("shrimp, lime", "clean, mix, ferment", "ceviche")],
     "Coastal Central America cures seafood in citrus like Peruvian cousin.",
     "Ceviche is Pacific coast — lime acid, cilantro, saltine crunch."),
    ("Riguas", "Nicaragua", "Ancient", 2, "grasses (maize)", "Grain",
     [s("fresh corn", "grind, wrap, heat", "riguas")],
     "Fresh corn cakes wrapped in corn husk grilled on comal.",
     "Riguas are Nicaraguan street — sweet corn, husk handle, charcoal."),
])

add("Sri Lankan", [
    ("String Hoppers", "Sri Lanka", "Medieval", 2, "grasses (rice)", "Grain",
     [s("rice flour", "press, steam", "string hoppers")],
     "Pressed rice noodle nests steamed for breakfast with curry.",
     "Idiyappam with curry is morning Sri Lanka — soft nest, coconut milk."),
    ("Lamprais", "Sri Lanka", "Modern", 4, "mixed", "Combined",
     [s("rice, meat, sambol", "wrap, heat", "lamprais")],
     "Dutch Burgher banana-leaf packet of rice, frikkadel, and sambol.",
     "Lamprais is Sunday parcel — baked leaf, mixed heritage, one plate."),
    ("Pol Sambol", "Sri Lanka", "Ancient", 1, "fruits (coconut)", "Combined",
     [s("coconut, chili, lime", "grind, mix", "pol sambol")],
     "Fresh coconut relish accompanies every Sri Lankan meal.",
     "Pol sambol is fire on coconut — chili, lime, fish flake optional."),
])

add("Icelandic", [
    ("Plokkfiskur", "Iceland", "Modern", 2, "fish", "Seafood",
     [s("cod, potato, béchamel", "boil, mix, heat", "plokkfiskur")],
     "Fish stew bound with white sauce — thrift from fishing villages.",
     "Plokkfiskur is Icelandic hug — mashed fish, rye bread, comfort."),
    ("Skyr", "Iceland", "Ancient", 1, "fermented", "Fermented",
     [s("skim milk", "ferment, strain", "skyr")],
     "Viking-era cultured dairy strained to thick yogurt-like cheese.",
     "Skyr is protein ancient — berry top, breakfast bowl, modern export."),
    ("Kjötsúpa", "Iceland", "Medieval", 2, "meat", "Meat",
     [s("lamb, root vegetables", "boil, simmer", "kjötsúpa")],
     "Lamb soup with rutabaga sustains Icelandic winters.",
     "Kjötsúpa is Sunday boil — lamb on bone, rutabaga sweet, simple."),
])

# ── RENDER ──────────────────────────────────────────────────────────────────
def render_dish(d: dict) -> str:
    rows = "\n".join(
        f"| {i+1} | {st['input']} | {st['techniques']} | {st['output']} |"
        for i, st in enumerate(d["stages"])
    )
    return f"""#### {d['name']}
- **Origin:** {d['culture']} · {d['region']}
- **Era:** {d['era']}
- **Difficulty:** {d['difficulty']}
- **Category:** {d['category']}
- **Primal source:** {d['primal']}

**Process**

| Stage | Input | Techniques | Output |
|-------|-------|------------|--------|
{rows}

**Historical context:** {d['history']}

**Cultural significance:** {d['significance']}

---
"""

def main():
    cultures: dict[str, list[dict]] = {}
    for dish in DISHES:
        cultures.setdefault(dish["culture"], []).append(dish)

    lines = [
        "",
        "## Part II: Regional Cuisine Compendium",
        "",
        "Expanded regional coverage: flagship dishes per culture using the canonical technique verb set.",
        "Ingredients outside current game primitives (meat, poultry, dairy) are noted for educational completeness.",
        "",
    ]

    culture_order = sorted(cultures.keys())
    for culture in culture_order:
        lines.append(f"### {culture}")
        lines.append("")
        for dish in cultures[culture]:
            lines.append(render_dish(dish))

    # Stats for appendix
    stats = {c: len(v) for c, v in cultures.items()}
    lines.append("## Appendix D: Regional Coverage Statistics")
    lines.append("")
    lines.append(f"**Total Part II dishes:** {len(DISHES)}")
    lines.append("")
    lines.append("| Culture | Dishes |")
    lines.append("|---------|--------|")
    for c in culture_order:
        lines.append(f"| {c} | {stats[c]} |")
    lines.append("")

    out_path = Path(__file__).parent / "recipes_part2_output.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(DISHES)} dishes across {len(cultures)} cultures to {out_path}")

if __name__ == "__main__":
    main()
