name: Auto-Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        run: gh pr merge "${{ github.event.pull_request.number }}" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
